### ISSUE TITLE
getAnnotationConnections Fails when Grabbing by parentId

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#179]
I attempted to grab connections using the getAnnotationConnections function using parentId as shown below.
`annotationClient.getAnnotationConnections(parentId=annotation['_id'])`
However, this resulted in the output of empty lists. Is this a bug or has grabbing connections by parentId not been implemented yet?

**Comment by zjniu** [comment]
The previous issue description still holds. It is still returning empty lists. However, using the datasetId worked before the update and still works.

**Comment by boucaud** [comment]
I just tested it on my end and it seems to work: 
![DeepinScreenshot_select-area_20220128113856](https://user-images.githubusercontent.com/1732912/151523478-31b444cd-db9e-4fe2-a237-06a0ba91a6dd.png)

Can you make sure you're using the latest version ?

Also, can you try converting the id to string before passing it, that may be the issue here ?

**Comment by boucaud** [comment]
Nevermind, I think I found the issue with the client. I pushed a fix now.
