### ISSUE TITLE
Rework configurations

### ISSUE THREAD

**Issue by bruyeret** [Kitware/UPennContrast#341]
Rework configurations:
- A configuration contains the following data: properties, tools, layers (annotations are per dataset)
- Each dataset has a default configuration when uploaded
- The user can create new configurations from a dataset
- The user can import configurations when the number of channels is the same
- The user can rename configurations
- The user can remove a configuration from a dataset
- When a configuration doesn't belong to any dataset it is unreachable and then definitly deleted and the properties, tools and layers are removed from the database (ask for confirmation before the last "remove from dataset" or "delete dataset")

**Comment by arjunrajlab** [comment]
After having a nice conversation with @bruyeret , here is a bit more of a specification for how data collections could work. The overall idea is that a collection is actually internally just a configuration. Configurations are now separate from datasets. Each configuration can apply to multiple datasets, and each dataset can be associated with multiple configurations. A "Collection" is just a configuration with multiple associated datasets.

What does a Configuration specify? Configurations consist of:
1. Layer definitions and contrast settings.
2. Tools
3. Properties
4. Locking: configurations can be "locked" so that changes are not saved. That way, people can play around without "messing up" the configuration.

Configurations are "compatible" with a dataset if:
1. If the XY dimension is either 1 or multiple: the configuration should specify
2. If the Z dimension is either 1 or multiple: the configuration should specify
3. If the T dimension is either 1 or multiple: the configuration should specify
5. Channels are the same: the configuration should specify

For instance, if a configuration was created for a dataset that had:
XY = 1…4, Z = 1, T = 1…10, channels BF, DAPI
Then it WOULD be compatible with 
XY = 1…8, Z = 1, T = 1…13, channels BF, DAPI
But would NOT be compatible with 
XY = 1, Z = 1, T = 1…13, channels BF, DAPI
XY = 1…4, Z = 1…20, T = 1…13, channels BF, DAPI

What might the interface look like?
When uploading data, it may be useful to have an option for importing multiple datasets. This would be different from multi-source. I envision the following if you selected multiple files when uploading:
1. After uploading, if there are multiple files, then have a radio button for either "Upload as a collection of datasets" or "Upload as a single multi-file dataset". 
2. If "Upload as a collection of datasets", then parse the first one as usual and expose the usual interface.
3. Then proceed with all of the Datasets having the same Configuration, assuming they pass the compatibility check.

Another way: people upload multiple datasets independently. Here is a workflow:
1. Someone uploads a single first Dataset.
2. They create a Configuration and view it.
3. They upload, separately, another Dataset, but to the same folder.
4. If the Dataset is compatible with the Configuration, that Configuration is selected as the default for viewing.

Another way: if a dataset is moved to a folder for which all Datasets have a particular configuration, then that configuration should be added to the dataset (if compatible).

In the NimbusImage viewer, if the Dataset is part of a Collection, then the Dataset should be a dropdown. The elements of the dropdown should be the different Datasets so that you can switch between them. Below that, there should be a button that says "Manage collection…", which brings up a dialog in which you can add compatible Datasets to the Collection via a file-browser like interface with checkboxes.

Here's an example of 3 files that could be a Collection:
https://www.dropbox.com/sh/zrn2dsrt1igjgmh/AAADGV4CjhMRM3ylXbQt1mIIa?dl=0

**Comment by arjunrajlab** [comment]
Also, ChatGPT4 had the following suggestion for an interface, which actually seems quite nice:

**Me:** _How would you design a user interface in which you have two types of objects, collections and datasets, and you want a user interface to select which datasets you want to associate with a particular collection?_

**ChatGPT4:**
Designing an effective user interface for managing collections and datasets requires a clear understanding of the user's goals, a logical structure, and a visually appealing design. Here's an outline of how you could design such a user interface:

Define the layout:

Use a two-pane layout with the left pane for collections and the right pane for datasets.
In the left pane, display a list of existing collections.
In the right pane, display a list of available datasets.
Collection pane:

Provide a search bar at the top of the collection pane to filter collections by name or other relevant attributes.
Display the list of collections in a scrollable list view, with each collection represented by a card or list item.
Each collection item should display its name and the number of associated datasets.
Add a "Create New Collection" button at the bottom of the pane to allow users to create new collections.
Enable users to select a single collection by clicking on the respective item. Highlight the selected collection to indicate it's active.
Dataset pane:

Provide a search bar at the top of the dataset pane to filter datasets by name or other relevant attributes
