### ISSUE TITLE
Contrast setting of snapshots

### ISSUE THREAD

**Issue by bruyeret** [Kitware/UPennContrast#443]
See [this comment](https://github.com/Kitware/UPennContrast/pull/439#issuecomment-1590815424)

**Comment by bruyeret** [comment]
There are two places where the contrast is saved:
- Each layer has a contrast in the configuration
- Each layer MAY have a contrast in the dataset view

The used contrast is: the dataset view contrast if defined, else the configuration contrast

When taking a Snapshot, the used contrast is saved
When opening a Snapshot, the configuration layers are set to be the saved one
This why you thought that the feature was broken: if you "reset to saved" each layer and then click the snapshot, it should work

There are two issues with the current approach:
- As you experienced, it is inconvenient to "reset to saved" each layer before clicking the snapshot
- The configuration is overwritten which may be a problem, for example if you fine tuned this configuration for other datasets

A first solution:
Set the dataset view contrast instead of overwritting the whole configuration
But the configuration may have changed: layers can be deleted, added, their channel may have changed...
As a result, the contrasts set in the dataset view won't correspond to a layer or the specified contrast won't make sense, and I don't know how I could fix this problem

Another solution is:
For the first issue, automatically "reset to saved" each layer
For the second issue, add a warning explaining that the configurations will be overwritten, and that the user can save the current configuration by taking a snaphot with every contrast reset to saved

What do you think @arjunrajlab ?

**Comment by arjunrajlab** [comment]
Ah, okay, that makes sense. I think for the first issue: yes, automatically doing "reset to saved" for each layer is fine. I think then just throwing an error or prompting the user is fine. I think the issue will come up relatively infrequently because usually people don't change the configuration/layers, etc.

Although now that I'm thinking about it more, I think actually just setting the dataset view contrast makes the most sense. I would just throw an error if the layers have changed (because layer changes are probably unlikely). Anyway, if someone is changing the layers, then the whole idea of the snapshot doesn't make much sense. I think if that happens, we can just allow the snapshot to just be the rectangle and all the other parts of the snapshot would be undefined (and perhaps marked with an exclamation point). So overall, solution 1.
