### ISSUE TITLE
Overview panel

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#450]
It would be helpful to have an overview panel like this one in the top left of the image that shows the overall image and a little box covering where the current field of view is. I believe @manthey already has something for this for histomicstk that he showed me recently.

<img width="581" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/c6d97b84-619e-4c9a-be3a-8555a2f99b9b">

**Comment by manthey** [comment]
In HistomicsUI (code here: https://github.com/DigitalSlideArchive/HistomicsUI/blob/master/histomicsui/web_client/panels/OverviewWidget.js), we made it so you can click on the overview image to change your view location and also drag the rectangle around to change your view.  

The overview image should probably be the fully composited set of layers.  That is, I think we want it to change as you turn layers on and off.  Unless we expose different compositing modes, this can be done as a single url to the server on a single layer on the overview rather than a layer on the overview per layer in the main viewer.

What happens when we unroll?

I assume we would reflect max-merge effects in the overview.

If we allow rotation of the image, then the overview should rotate the same way (we tried keeping it fixed but that was unintuitive).

**Comment by arjunrajlab** [comment]
Agreed, overview should be fully composited set, matching the image.

Interesting question about the unroll. One option could be to just have the overview on each panel. Another could be to keep the composite in just one of them (top left?). I tend to think the first option might be better, but either is fine depending on what is easier to implement and doesn't affect performance as much.

Max-merge should apply to overview as well, I think.

Interesting point about rotation as well. Rotating the overview makes sense, and in fact would probably be very helpful for people because when they rotate, they seem to have a hard time knowing what is happening.
