### ISSUE TITLE
Artifact with image display

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#631]
We are having an issue with image display with an artifact of a vertical line:

<img width="1577" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/f8fe72c4-7498-4f4f-bad0-beb175089d38">

This showed up on another file as well recently (the very large "Golnaz" dataset), but this dataset is a lot easier to work with. Here's a link to the dataset:
https://www.dropbox.com/scl/fi/e471z4mu0v4hbtxsc4qae/slide1_2_fluor.nd2?rlkey=emarbyg1q7g3dbt2bfo3kd7kv&dl=0

I also uploaded here to nimbusimage.com:
https://nimbusimage.com/#/datasetView/65b7c46adda92c449e614cce/view?z=5

Send login details to @manthey

**Comment by arjunrajlab** [comment]
Some more images. Seems to go away when you zoom in.

<img width="1556" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/ba7aa567-78c8-4cd6-8ebd-1a24921d63b0">

<img width="1577" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/1727e06b-7c15-4f37-a553-b7267386ee77">

**Comment by manthey** [comment]
This: https://github.com/girder/large_image/pull/1447 will fix the issue.

The issue occurred because when the multi-source source composites images, it now can do general transformations.  If a simple power of two scaling is sufficient this is bypassed (which was only the behavior before https://github.com/girder/large_image/pull/1415).  The detection on if the basic scaling or the general transform was needed used the general transform needlessly.  PR 1447 fixes that.

The actual issue is that when the general transform is applied, an alpha channel is added when needed.  On this sample, at anything other than the full resolution, this alpha channel exists for right/bottom edge tiles.  The autoscaling for intensity was using this, so the non-edge tiles were fine, but the right/bottom edge tiles were too dark, since the autoscaling didn't apply the same way when a full range alpha channel exists.  The alpha channel could also have been skipped (for this image which has one band or sample per pixel) by adding `singleBand: true` to the multi-source yaml/json file.

More generally, there should probably be a specification in the multi-source to "addAlphaBand: true/false/asneeded" or something to make this behavior more explicit and controllable.
